base {
    log_debug = off;
    log_info = on;
    log = "syslog:daemon";
    daemon = on;
    redirector = iptables;
    redsocks_conn_max = 4096;
    connpres_idle_timeout = 7440;
    max_accept_backoff = 6000;
}

redsocks {
    local_ip = 0.0.0.0;
    local_port = 12345;
    ip = 127.0.0.1;
    port = 1080;
    type = socks5;
    listenq = 4096;
    splice = true;
}
